version: '3.8'

services:
  apache_php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache_php
    restart: always
    volumes:
      - .:/var/www/tools.africacdc.org/tools/public_dashboards
    ports:
      - "808:80"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    depends_on:
      - mysql_client
    networks:
      - app-network
    working_dir: /var/www/tools.africacdc.org/tools/public_dashboards
   

  mysql_client:
    image: mysql:5.7.42
    platform: linux/amd64
    container_name: mysql_client
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
